#+title: Codex

# Include additional CSS styles. Sadly the readtheorg theme does not appear to
# come bundled with Haskell syntax colors, so we have to generate these ourselves.
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="syntax-highlighting.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

# Set default header argument for all source code blocks. The "no-export" means
# that we do not expand noweb references when exporting (weaving) --- the fact
# that this is not the default option is odd.
#+PROPERTY: header-args :noweb no-export

# Number the top 5 levels of headings; since h1 is the title, this means headings
# up to 4 numbers --- e.g., "1.2.3.4".
#+OPTIONS: H:5

#+BIBLIOGRAPHY: ./citations.bib

* Introduction

This project aims to capture my notes for studying various programming problems (data structures and algorithms).

* Layout

Every problem gets its own =.org= file. The solutions are all in Python. All solutions are "standalone" in that none of them use any libraries other than what's provided by Python's standard libraries.

Below is a table of every problem, with tags that give a brief description of each one.

#+ATTR_HTML: :border 2 :cellpadding 6 :rules all :frame border
| Name                | Tags                | Sources                 |
|---------------------+---------------------+-------------------------|
| [[file:problem/parity/README.org][Parity]]              | bitwise             | [cite:@epip 27; @hd 96] |
| [[file:problem/rectangle_overlap/README.org][Rectangle overlap]]   | geometry            | [cite:@epip 39]         |
| [[file:problem/rearrange_list_even_odd/README.org][Rearrange list]]      | array, partitioning | [cite:@epip 41]         |
| [[file:problem/dutch_national_flag/README.org][Dutch national flag]] | array, partitioning | [cite:@epip 43]         |

* Literate Programming Build System

#+include: "build-literate.org" :lines "2-"

* References

#+begin_src bibtex :tangle citations.bib :eval no :exports none
@book{epip,
    title = {Elements of Programming Interviews in Python: The Insiders' Guide},
    isbn = {9781537713946},
    shorttitle = {Elements of Programming Interviews in Python},
    language = {eng},
    publisher = {CreateSpace Independent Publishing Platform (15 Sept. 2016)},
    author = {Aziz, Adnan and Lee, Tsung-Hsien and Prakash, Amit},
    month = sep,
    year = {2016},
    note = {OCLC: 1308498466},
}

@book{hd,
    title = {Hacker's Delight},
    edition = {2nd ed},
    isbn = {9780321842688},
    publisher = {Addison-Wesley},
    author = {Warren, Henry S.},
    year = {2013},
    keywords = {Computer programming},
    address = {Upper Saddle River, NJ},
}
#+end_src

#+CITE_EXPORT: csl ~/prog/codex/deps/styles/ieee.csl
#+PRINT_BIBLIOGRAPHY:
