#+title: Buy and sell stock once
#+SETUPFILE: ../../lilac.theme
#+PROPERTY: header-args :noweb no-export
#+OPTIONS: H:5

#+BIBLIOGRAPHY: ../../citations.bib

* Problem statement

Given a list of prices for a stock over the past N days (one price per day),
determine the optimum days to buy and sell the stock once to maximize profit
[cite:@epip 51].

** Inputs and outputs

- Input: list of stock prices (positive numbers)
- Output: day to buy the stock, day to sell the stock, and the realized profit
  margin

* Insights

Simply taking the minimum and maximum values of the entire range, and comparing
these two numbers, won't work. Example: =[10, 5]=. Here the only possible buy
and sale is to buy at price =10= and sell on the next day at price =5=. But
doing so would result in a loss. If the price is decreasing each day, then
/every/ possible buy/sell combination will result in a loss. In this situation
the algorithm should not recommend a buy/sell transaction at all (do nothing).

Here's another example: =[10, 9, 8, 1, 2, 6]=. Here the maximum possible profit
is to buy at =1= and sell at =6=, for a profit margin of =5=. The minimum and
maximum prices are =1= and =10=, which are interesting but don't give us the
answer.

* Solutions

** Brute force

Compare every number in the list with every other number. That is, compute every
possible combinationa of buy/sell dates, and just return the best (max profit)
dates found.

#+name: __NREF__brute_force
#+begin_src python
def brute_force(prices: list[int]) -> Optional[tuple[int, int, int]]:
    if not prices:
        return None

    max_profit_so_far = 0
    for buy_date, price_buy in enumerate(prices):
        for sell_date in range(buy_date + 1, len(prices)):
            profit = prices[sell_date] - price_buy
            if profit > max_profit_so_far:
                max_profit_so_far = profit
                transaction_dates = (buy_date, sell_date, profit)

    if max_profit_so_far:
        return transaction_dates

    # If no profitable trade found, return None.
    return None
#+end_src

The time complexity is $O(n^2)$ where $n$ is the length of the list of prices.

** Optimal

For the optimal solution, the key is to pretend to sell on that day, using the
minimum price found in the previous days as the buying point. The trick here is
that the previous minimum price calculation can be updated on each iteration
with just a single =min()= comparison.

#+name: __NREF__optimal
#+begin_src python
def optimal(prices: list[int]) -> Optional[tuple[int, int, int]]:
    if not prices:
        return None

    min_price_so_far = float('inf')
    max_profit = 0

    for date, price in enumerate(prices):
        if price < min_price_so_far:
            buy_date = date
            min_price_so_far = min(price, min_price_so_far)

        max_profit_if_sell_now = price - min_price_so_far
        max_profit_prev = max_profit
        max_profit = max(int(max_profit_if_sell_now), max_profit)

        if max_profit > max_profit_prev:
            transaction_dates = (buy_date, date, max_profit)

    if max_profit:
        return transaction_dates

    # If no profitable trade found, return None.
    return None
#+end_src

The time complexity is $O(n)$.

* Tests

#+name: Tests
#+caption: Tests
#+begin_src python :eval no :session test :tangle (codex-test-file-name)
from hypothesis import given, strategies as st
import unittest

from typing import Optional

__NREF__brute_force

__NREF__optimal

class Test(unittest.TestCase):
    cases = [
        ([],                      None),
        ([0],                     None),
        ([0, 0, 0, 0],            None),
        ([3, 2, 1],               None),
        ([5, 25, 100, 50],        (0, 2, 95)),
        ([5, 25, 100, 1, 50, 99], (3, 5, 98)),
    ]

    def test_simple_cases(self):
        for given_prices, expected in self.cases:
            self.assertEqual(brute_force(given_prices), expected)
            self.assertEqual(optimal(given_prices), expected)

    @given(st.lists(st.integers(min_value=1, max_value=100), min_size=0,
                    max_size=14))
    def test_random(self, given_prices: list[int]):
        got = brute_force(given_prices)

        # If the prices were not always decreasing, then there must have been
        # some optimum buy/sell date.
        if given_prices and max(given_prices) > given_prices[0]:
            self.assertNotEqual(got, None)

        # Check that the optimal solution agrees with brute force.
        self.assertEqual(optimal(given_prices), got)

if __name__ == "__main__":
    unittest.main(exit=False)
#+end_src

#+begin_src python :tangle __init__.py :exports none
#+end_src

* References
#+CITE_EXPORT: csl apa.csl
#+PRINT_BIBLIOGRAPHY:
